---
- hosts: java_server
  become: yes  # Run as sudo/root
  tasks:
    - name: apt package update
      apt:
        update_cache: yes

    - name: Installing Tomcat Apache
      apt:
        name: apache2
        state: present

    - name: Start and Enabling Apache2
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Enable Port 80 
      ufw:
        rule: allow
        port: "80"
        proto: tcp
